### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by cmsessa** [jyrkiput/Hudson-Gerrit-Plugin#1]
After building, the plugin tries to approve a commit but I get this:

Connection timed out
java.net.ConnectException: Connection timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
    at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
    at java.net.Socket.connect(Socket.java:529)
    at java.net.Socket.connect(Socket.java:478)
    at java.net.Socket.<init>(Socket.java:375)
    at java.net.Socket.<init>(Socket.java:189)
    at com.sshtools.j2ssh.net.SocketTransportProvider.<init>(Unknown Source)
    at com.sshtools.j2ssh.net.TransportProviderFactory.connectTransportProvider(Unknown Source)
    at com.sshtools.j2ssh.SshClient.connect(Unknown Source)
    at com.sshtools.j2ssh.SshClient.connect(Unknown Source)
    at hudson.plugins.gerrit.ssh.SSHMarker.connect(SSHMarker.java:32)
    at hudson.plugins.gerrit.GerritNotifier.verifyGerrit(GerritNotifier.java:155)
    at hudson.plugins.gerrit.GerritNotifier.perform(GerritNotifier.java:201)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
    at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:600)
    at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:580)
    at hudson.maven.MavenModuleSetBuild$RunnerImpl.post2(MavenModuleSetBuild.java:598)
    at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:528)
    at hudson.model.Run.run(Run.java:1264)
    at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:306)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:122)
Finished: ABORTED

Is there a way to get any info of what's happening.
I can't make it work.

**Comment by cmsessa** [comment]
Solved. I had the wrong port for Gerrit.
All the same it would be nice to get some kind of info.

Thanks for the plugin.

**Comment by jyrkiput** [comment]
Great that you got it working, I'll check if I can add some info. And I'm sorry that it took a while for me to answer, I've been offline for a while.
